### ISSUE TITLE
Room name

### ISSUE THREAD

**Issue by Supermanu** [SergioComeron/moodle-mod_jitsi#10]
Hi,
Thanks a lot for this plugins! I have an issue with the room creation in the jitsi server. The jitsi room name has dots from the moodle course in its name and thus it is not created on the jitsi server (which works perfectly if I use it directly without dots).
I'm surely doing something wrong at some point. Any hints?

**Comment by SergioComeron** [comment]
Hi @Supermanu 
Thanks a lot for trying the plugin. Can you give me the shortname of the course and name of the session to be able to reproduce it?

**Comment by Supermanu** [comment]
Thanks for this quick answer!
The shortname of the course is `QFT` and the name of the session is `QFT.Test.1`.

**Comment by Befisch** [comment]
Hi guys,

to save you both some time (first of all thank you for the plugin)
in view.php line 77
`$urlparams = array('avatar' => $avatar, 'nom' => $USER->username, 'ses' => $course->shortname.'.'.$jitsi->name.'.'.$jitsi->id, 'courseid' => $course->id, 'cmid' => $id);`
change the commas to nothing.
This is indeed no plugin bug. It is a Jitsi naming issue. You can not create rooms with dashes kommas underscores ....

We changed it to:
`$urlparams = array('avatar' => $avatar, 'nom' => $USER->username, 'ses' => $course->shortname.$jitsi->name.$jitsi->id, 'courseid' => $course->id, 'cmid' => $id);`

Is perhaps not the best solution but for current demand perhaps the fastest.

Best regards :)

**Comment by SergioComeron** [comment]
Hi @Befisch , 
thanks for your help. I think that @Supermanu reports is he cannot enter the room. You can enter to the session? your problem is just that in the title you don't see the dots?

**Comment by Supermanu** [comment]
Thanks @Befisch, your change fixed the error. It is in deed an error from Jitsi and not directly related to the plugin itself which works very well by the way.

**Comment by Befisch** [comment]
Hi @SergioComeron 
no our problem was that the jitsi server was not able to create the room at all, because jitsi room name doesn't allow dots in the name.

So the problem is I think not with your plugin at all but with the jitsi server.
For us "testcourse.test.1" didn't work but "testcoursetest1" did.

Hope that clarifies :)

**Comment by tobiasreischmann** [comment]
We have the same issue. Simply removing the dots will not work in all cases, as well.
We, at least, have a standard course shortname template which includes _ and - on a regular basis.
A colleague of mine found this in jitsi code:
const _ROOM_EXCLUDE_PATTERN = '[\:\?#\[\]@!$&\'()*+,;=></"]';
Interestingly, there is no '.' nor a '_'. Nevertheless, it would be nice i guess to automatically remove all unallowed characters from the session string.

**Comment by SergioComeron** [comment]
Hi guys, 
sorry but I can't reproduce the error.
In our production environment we have courses with points in their shortname (example sergio.comeron) and I create an activity with name test.1 and I have no problem launching the session ... Does this fail you?
<img width="766" alt="cap1" src="https://user-images.githubusercontent.com/14803178/76985134-0de29d00-6940-11ea-812d-9b412dc1b13a.png">
<img width="766" alt="cap2" src="https://user-images.githubusercontent.com/14803178/76985342-5f8b2780-6940-11ea-8aea-5a39821dbaa0.png">

**Comment by tobiasreischmann** [comment]
I think it is mainly a configuration issue of the jitsi server. We are using our own, which is a scaling installation setup in 2 days. Possible that something went wrong there. 
https://meet.jit.si/ does support colons, dashes, underscores and everything. 
I will fix it for now locally, since it is easier than searching the bug in the jitsi configuration.
If anyone else has these issues, this commit should solve the problem for any course shortname out there:
https://github.com/learnweb/moodle-mod_jitsi/commit/87bb9ab78a114f1184a162ad68a3272f03aefda3

**Comment by SergioComeron** [comment]
ok, 
anyway I will try to do something also the plugin so that this problem does not exist. Tonight or tomorrow I will release a new version with some improvements.
thanks guys

**Comment by tobiasreischmann** [comment]
We solved the problem with our jitsi installation:
The config of the nginx in "docker-jitsi-meet" allows only rooms with "^/([a-zA-Z0-9=\?]+)$". We used some aspects of https://github.com/jitsi/jitsi-meet/blob/master/doc/debian/jitsi-meet/jitsi-meet.example . There they first catch static files (etc.) through defaults and try_files. Everything else is then interpreted as a room name.

**Comment by SergioComeron** [comment]
Hi guys, 
as @tobiasreischmann  says it finally seems like it's a jitsi server problem. Anyway, I have put in the new version to be able to choose the separator.
Thank you all for contributing.
