### ISSUE TITLE
Sesion does include meet.jet.si API

### ISSUE THREAD

**Issue by tobiasreischmann** [SergioComeron/moodle-mod_jitsi#11]
Is there a reason, why the external_api is not requested from the jitsi_domain from the config?
https://github.com/SergioComeron/moodle-mod_jitsi/blob/f59b4336bd4493328120dfb4d4aa5e19d146415e/sesion.php#L51

**Comment by SergioComeron** [comment]
Hi @tobiasreischmann, 
it is true, we could use that of our server perfectly. I leave it for the next version. Thank you!

**Comment by SergioComeron** [comment]
Hi @tobiasreischmann,
the last version already use the api of your own server. Thanks!
