### ISSUE TITLE
Refused to connect

### ISSUE THREAD

**Issue by yannicklebras** [SergioComeron/moodle-mod_jitsi#12]
Hi, 
Thank you for the plugin. I had the same issue as #10 and solved it by editing view.php.
But now I'm facing anther issue : it says that my server refused to connect and I get the following error in the chrome console : 
Refused to display 'https://meet.myserver.com/DimensionfinieQuestionsReponses1' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

Any idea how to solve it ? 

Thank you,

Yannick

**Comment by yannicklebras** [comment]
Ok, i found the problem it was an nginx conf probleme. Solved, sorry.
It is now working fine.

**Comment by SergioComeron** [comment]
Sorry for not answering yesterday. I'm glad it was fixed.
