### ISSUE TITLE
Jitsi plugin issue with Youtube sharing

### ISSUE THREAD

**Issue by sourish20** [SergioComeron/moodle-mod_jitsi#14]
Hello!

I am facing this issue with the plugin.

If I enable the Youtube sharing option in plugin settings, I can't open the conference in Moodle. If I click on Access button, it's just a white screen.

If I disable this option in plugin settings page, then it's working fine.  I can open the conference.

But I am not facing any issue with the Youtube sharing in the standalone Jitsi server I have setup recently. 

I have setup my own Jitsi server.

Moodle 3.8.2+ (Build: 20200327)

Jitsi Plugin: v2.2 (2020032800)

![jitsi_packges](https://user-images.githubusercontent.com/63064229/78273332-4f706c00-752c-11ea-8640-cade5afe7603.png)

![s1](https://user-images.githubusercontent.com/63064229/78274107-55b31800-752d-11ea-8fa2-efd5beec6938.png)

![s2](https://user-images.githubusercontent.com/63064229/78274117-58ae0880-752d-11ea-8d60-68e148efc432.png)

![s3](https://user-images.githubusercontent.com/63064229/78274127-5b106280-752d-11ea-91c5-f3c8f56785a5.png)

![s4](https://user-images.githubusercontent.com/63064229/78274293-9f036780-752d-11ea-9078-d192b515bc78.png)

![s5](https://user-images.githubusercontent.com/63064229/78274299-a1fe5800-752d-11ea-9a36-3bd3e34a20a5.png)

**Comment by SergioComeron** [comment]
Hi @sourish20, 
thanks for open the issue.
Can you tell me the error it shows in the browser console?

**Comment by sourish20** [comment]
Here it is:

![jit_err_1](https://user-images.githubusercontent.com/63064229/78325392-14eee980-7595-11ea-985b-2a1d6694ba96.png)

![jit_err_2](https://user-images.githubusercontent.com/63064229/78325397-18827080-7595-11ea-9a62-454e926420ba.png)

**Comment by SergioComeron** [comment]
ok, the problem is that there are missing single quotes in the variable. Today or tomorrow I launch an update with the solution to this problem. Thank you!

**Comment by sourish20** [comment]
Thank you Sergio!

**Comment by SergioComeron** [comment]
Solve with 2.3
Thanks!

**Comment by sourish20** [comment]
Thanks a lot Sergio!

**Comment by sourish20** [comment]
There is another issue with the latest plugin now -

1.) Watermark appearing at the top right even if I remove the watermark url from plugin settings.

2.) Local Recording button is disabled though it's enabled in the standalone server.

![jitsi_mdl_plug_1](https://user-images.githubusercontent.com/63064229/78454491-e6b4fb00-76b5-11ea-87d0-79593b75f350.png)

![jitsi_mdl_plug_2](https://user-images.githubusercontent.com/63064229/78454495-ea488200-76b5-11ea-8992-58c002f2102c.png)

![jitsi_mdl_plug_3](https://user-images.githubusercontent.com/63064229/78454496-ecaadc00-76b5-11ea-89f4-4f86bfd64d10.png)

**Comment by SergioComeron** [comment]
Hi @sourish20 , 
the watermark link isn't a link to an image, it is a link to a web page when you click on the watermark. A watermark will always appear unless you configure it on the server.

about the recording button... It is strange, because in the plugin I don't touch anything on that button, if you have it configured on the server it should appear.

**Comment by sourish20** [comment]
Hello!

I have already disabled the watermark in my server as you can see from the 1st screenshot. There is not watermark there. But it's visible in Moodle. This was not the case with previous plugin version i.e. 2.2

Yes, I have configured the recording button in my server and it's enabled. Please see the screenshots. Specially the 1st one. I have already written and highlighted it. I guess the local recording toolbar button is not enabled in the plugin code.

**Comment by opentectaranto** [comment]
Hi Sergio I'm Gaetano from ITALY.
I have Moodle 3.8.2 and your last plugin (mod_jitsi_moodle38_2020040900.zip).
I have a problem with YouTube sharing function: with Google Chrome (last version) youtube's video frozen, with Mozilla Firefox all OK.

Can you help me?
Regards.

**Comment by SergioComeron** [comment]
Hi @opentectaranto 
Are you using your own jitsi server or the meet.jit.si public server? Having the same problem if you don't use the plugin? that is, if you create a session directly without doing it in Moodle?

**Comment by opentectaranto** [comment]
Hi Sergio, I use public server.
I tried also the last mod_jitsi_moodle38_2020041300.zip, same problem with Google Chrome. With Firefox all work fine.

Directly on Jitsi Meet, without Moodle and your Plug-In, Google Chrome work fine.

If you prefer, I can send credential to my system.
Regards.
Gaetano
