### ISSUE TITLE
No audio, no camera

### ISSUE THREAD

**Issue by marconte21870** [SergioComeron/moodle-mod_jitsi#15]
Tanks very much for plug-in  very nice....
I have installed Jitsi 2.2 e Moodle 3.8+.
In my vps server in Ubuntu 18.04 and nginx.
Jitsi run on https in a domain with letsencrypt and all ok camera and microphone is ok.
Moodle run on sub domain in the same server not https and run very well but if insert a Jitsi activity and access in the Moodle not start microphone and camera.
Why?
Image is like this
![493CD65A-8112-4EE6-B155-F6B872D0E4AF](https://user-images.githubusercontent.com/63079840/78310641-d33b5000-754e-11ea-90b3-151cdf193c53.png)

**Comment by marconte21870** [comment]
Resolved
I have installed also https certificate with letsencrypt in subdomain , in virtualhost of nginx ssl on;
 in listen port 443 for moodle host and jitsi host and all is ok
![ok](https://user-images.githubusercontent.com/63079840/78349494-fb08d300-75a3-11ea-8a4e-1672266ef447.png)

**Comment by SergioComeron** [comment]
Ok @marconte21870 
Thanks for the info!
