### ISSUE TITLE
Multiple available roles for moderator

### ISSUE THREAD

**Issue by bozicm** [SergioComeron/moodle-mod_jitsi#18]
As far as I understand the code in `view.php` there is currently only `editingteacher` is permitted to be assigned as moderator in Jitsi. Would it be possible for plugin to look into the available roles and let the Moodle admin to fill in the checkboxes for roles that can be to be moderators and then let the plugin dynamically check and select one upon clicking the Access button?

**Comment by SergioComeron** [comment]
Hi @bozicm ,
It is a good idea, I had to implement the idea of moderation quickly, but as you say, not only the teacher may want to have moderation. It is a feature that I will implement in the next versions.

**Comment by SergioComeron** [comment]
Hi, 
now with new version moderation it's a capability of the module.
You can allow the capacity for the role you want

**Comment by bozicm** [comment]
Many thanks!
