### ISSUE TITLE
Error, after clicking the "Access" button to start a session

### ISSUE THREAD

**Issue by nadavkav** [SergioComeron/moodle-mod_jitsi#2]
A required parameter (courseid) was missing
More information about this error

×Debug info: 
Error code: missingparam
×Stack trace:
line 494 of /lib/setuplib.php: moodle_exception thrown
line 566 of /lib/moodlelib.php: call to print_error()
line 34 of /mod/jitsi/sesion.php: call to required_param()

---
It seems that no course module id is passed to the 
$context = context_module::instance($courseid);
(/mod/jitsi/sesion.php L46)

Suggest passing a $cmid to that page, and use it instead of $courseid

**Comment by SergioComeron** [comment]
Hi nadavkav, 
thanks for your comments. 
I can't get the error you tell me. How did you get it? 
Anyway, I think that your way of seeing the context is the correct one with the $ cmid. I'm going to try it and I'll take your solution.

**Comment by SergioComeron** [comment]
Hi nadavkav, 
I merged this to the master branch.

Thanks!

**Comment by SergioComeron** [comment]
I have uploaded a new version to the repository with your improvements. Thank you!
Finally I was able to get the error, but it is already solved thanks to you. Thanks, again! :)

**Comment by nadavkav** [comment]
Thank you @SergioComeron for a very useful and beautiful plugin :-)
