### ISSUE TITLE
jitsi plugin requesting for id and token

### ISSUE THREAD

**Issue by raymmedic** [SergioComeron/moodle-mod_jitsi#25]
Hello, I have been able to configure prosody to authenticate users via ldap. Meeting can be started and authenticated from the server directly. However from the moodle plugin, it is asking for id and token. 
How is that configured? 

Regards

**Comment by SergioComeron** [comment]
Hi @raymmedic,
The token configuration (app_id and secret) in the plugin should only be configured if you have the jitsi server configured for the use of token. If as you say you have it configured with ldap you should leave these parameters empty. So when you log into Moodle jitsi would ask you for the ldap username and password. Isn't it working like this?

**Comment by moodlebeuth** [comment]
@SergioComeron: But in this case the first moodle user who is opening the jitsi room via mod_jitsi has to log ons again before entering the conf room. How an I prevent this? With a subdomain of the jitsi server for authentication with JWT?

**Comment by SergioComeron** [comment]
Hi @moodlebeuth ,
that's. If you want to avoid that the user has to log in again, you need to use tokens to give him moderation.
You need to configure the server for use. The official guide is this: https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/tokens.md, but we did it using this plugin: https://github.com/nvonahsen/jitsi-token-moderation-plugin
As this is a server configuration issue I close this issue. If you have problems with the configuration, I recommend that you use the jitsi forums or their github.
Thanks!
