### ISSUE TITLE
Implementación en moodle

### ISSUE THREAD

**Issue by BorjadelaCamara** [SergioComeron/moodle-mod_jitsi#30]
Buenas tardes Sergio,
trabajo en un colegio y estamos tratando de usar el plugin de jitsi como herramienta de videoconferencia con nuestros alumnos a través de Moodle 3.5.2+
Por desgracia, no poseemos un servidor propio en el que instalar la aplicación server. ¿Habría alguna manera de poder usar tu plugin sin tener un servidor propio, usando los servidores de jitsi meet? 
Muchas gracias de antemano por tu tiempo y dedicación. 
Un saludo

**Comment by SergioComeron** [comment]
Hola @BorjadelaCamara, 
Puedes usarlo sin problema con el servidor de Jitsi Meet (meet.jit.si) tan solo tienes que informar ese dominio cuando instales el plugin. De hecho cuando lo instalas creo que en la administración te aparece ese por defecto. 
Con eso no tendrías que tener ningún problema. Lo único que al ser el servidor público no tienes posibilidad de usar los token y no podrías hacer que los estudiantes no fuesen moderadores.

¿Has probado a hacerlo y no te ha funcionado con el servidor publico?

**Comment by BorjadelaCamara** [comment]
Gracias por responder Sergio,

Si lo probé a instalar y lo configuré con el servidor de meet, pero no se por qué el iframe dentro de Moodle de funcionaba. Esto fue el lunes, día 13, y lo que estábamos haciendo era copiar por url a los chicos dentro de Moodle, y se abría fuera de Moodle la página de jitsi.meet.si. Pero acabo de volver a instalar el plugin para hacerte unas capturas y que tuvieras más información y ha funcionado a la primera.

Muchísimas gracias por la rapidez en el correo.

Borja de la Cámara


De: Sergio Comerón<mailto:notifications@github.com>
Enviado: viernes, 17 de abril de 2020 19:11
Para: SergioComeron/moodle-mod_jitsi<mailto:moodle-mod_jitsi@noreply.github.com>
CC: BorjadelaCamara<mailto:borjadelacamara@hotmail.es>; Mention<mailto:mention@noreply.github.com>
Asunto: Re: [SergioComeron/moodle-mod_jitsi] Implementación en moodle (#30)


Hola @BorjadelaCamara<https://github.com/BorjadelaCamara>,
Puedes usarlo sin problema con el servidor de Jitsi Meet (meet.jit.si) tan solo tienes que informar ese dominio cuando instales el plugin. De hecho cuando lo instalas creo que en la administración te aparece ese por defecto.
Con eso no tendrías que tener ningún problema. Lo único que al ser el servidor público no tienes posibilidad de usar los token y no podrías hacer que los estudiantes no fuesen moderadores.

¿Has probado a hacerlo y no te ha funcionado con el servidor publico?

**Comment by SergioComeron** [comment]
Si, había un problema con las versiones anteriores a la 3.6 que con algunos temas no funcionaba bien. Pero lo corregí en una de las últimas versiones. 
Me alegro de que os funcione :)

**Comment by BorjadelaCamara** [comment]
Perdona que te moleste Sergio otra vez, una pregunta técnica. No aparecen la opción de poner contraseña. Entiendo que una vez la persona que crea la sesión la cierra, los alumnos no pueden volver a entrar a ese canal. Es decir, hay alguna manera de bloquearlo para que no accedan a él, cuando no está el profesor???

Muchas gracias.

De: Sergio Comerón<mailto:notifications@github.com>
Enviado: viernes, 17 de abril de 2020 19:38
Para: SergioComeron/moodle-mod_jitsi<mailto:moodle-mod_jitsi@noreply.github.com>
CC: BorjadelaCamara<mailto:borjadelacamara@hotmail.es>; Mention<mailto:mention@noreply.github.com>
Asunto: Re: [SergioComeron/moodle-mod_jitsi] Implementación en moodle (#30)


Si, había un problema con las versiones anteriores a la 3.6 que con algunos temas no funcionaba bien. Pero lo corregí en una de las últimas versiones.
Me alegro de que os funcione :)
