### ISSUE TITLE
JS error when installing v1.8 under Moodle 3.5.11

### ISSUE THREAD

**Issue by mauritslamers** [SergioComeron/moodle-mod_jitsi#9]
I had trouble getting version v1.8 to work under Moodle 3.5.11 because of a JS error. In sesion.php, javascript code is injected to initialise the jitsi application but for some reason there are two options depending on the configured branch.

https://github.com/SergioComeron/moodle-mod_jitsi/blob/master/sesion.php#L56
```php
if ($CFG->branch < 36) {
    echo "parentNode: document.querySelector('#region-main .card-body'),\n";
} else {
    echo "parentNode: document.querySelector('#region-main'),\n";
}
```
For some reason, the code takes the first branch where it should have taken the second, as the result of `document.querySelector('#region-main .card-body')` is null.
When the jitsi app is initialising itself, it tries to append itself to null, which of course causes an error.

**Comment by SergioComeron** [comment]
Hi @mauritslamers, 
I'm going to review it to see what may be happening. I will inform you.
Thanks for the warning!

**Comment by nomisge** [comment]
I get following error on the console:

```
external_api.js:1 Uncaught TypeError: Cannot read property 'appendChild' of null
    at $._createIFrame (external_api.js:1)
    at new $ (external_api.js:1)
    at sesion.php:223
```
also using Moodle 3.5.x.
Might this be the same cause?

**Comment by mauritslamers** [comment]
Yep, it is still the same issue. I hadn't had time to update here that I still had the issue. I applied the same fix as above to get it to work.

**Comment by SergioComeron** [comment]
Hi @mauritslamers 
what fix has applied?

**Comment by mauritslamers** [comment]
The problem is the .card-body class selector. By removing that selector:

```
if ($CFG->branch < 36) {
    echo "parentNode: document.querySelector('#region-main'),\n";
} else {
    echo "parentNode: document.querySelector('#region-main'),\n";
}
```

I can get Jitsi working. So, for some strange reason, $CFG->branch is always < 36.

**Comment by SergioComeron** [comment]
ok, i think the problem is related to the theme we use, which theme do you use?

**Comment by kantgym** [comment]
That could be it, I'm using the Snap theme.

**Comment by kfern** [comment]
Same here with Clean Theme

**Comment by SergioComeron** [comment]
Hi @kfern , 
Which version of moodle? less than 3.6?

**Comment by kfern** [comment]
Hi @SergioComeron. Yes. Moodle 3.5.6

**Comment by mandadimuralidharreddy** [comment]
a simple workaround for this add this below line at line no :148 in mod/jitsi/sesion.php
`echo "parentNode:document.body,";`

**Comment by SergioComeron** [comment]
Hi guys, 
Can you test if Moodle-mod-jitsi_#9 branch solves the problem with your themes and old versions of moodle?

**Comment by kantgym** [comment]
Just did a quick test, seems to be working for me.

**Comment by SergioComeron** [comment]
I merged the branch and should be solve the problem with some themes on old versions moodle. 
The next version will bring the change. thanks
